### ISSUE TITLE
v0.0.10

### ISSUE THREAD

**Issue by henomis** [henomis/lingoose#102]
**Tasks**
- [x] use pinecone-go v1.1.2 https://github.com/henomis/lingoose/pull/104
- [x] use qdrant-go v1.0.2 https://github.com/henomis/lingoose/pull/104
- [x] integrate cohere use [henomis/go-cohere](https://github.com/henomis/cohere-go) https://github.com/henomis/lingoose/pull/103
- [x] implement cohere embedder https://github.com/henomis/lingoose/pull/108
- [x] implement cohere rerank https://github.com/henomis/lingoose/pull/106, https://github.com/henomis/lingoose/pull/107
- [x] implement cohere generate as LLM https://github.com/henomis/lingoose/pull/103
- [x] implement batching request (https://platform.openai.com/docs/guides/rate-limits/batching-requests) https://github.com/henomis/lingoose/pull/105
- [x] refactor and document https://github.com/henomis/lingoose/pull/109
- [x] Add localai example https://github.com/henomis/lingoose/pull/111
