### ISSUE TITLE
release v0.0.3

### ISSUE THREAD

**Issue by henomis** [henomis/lingoose#25]
**Tasks**

- [x] use new documentation template
- [x] add linter to github actions https://github.com/henomis/lingoose/pull/26
- [x] Refactor pipeline input and ouput https://github.com/henomis/lingoose/pull/27
- [x] Add splitter https://github.com/henomis/lingoose/pull/28
- [x] move docs to a different branch https://github.com/henomis/lingoose/pull/29
- [x] refactor prompt interface https://github.com/henomis/lingoose/pull/30
