### ISSUE TITLE
release v0.0.4

### ISSUE THREAD

**Issue by henomis** [henomis/lingoose#31]
**Tasks**

- [x] :lady_beetle:  fix metadata deep copy  https://github.com/henomis/lingoose/pull/32
- [x] Don't store documents content as metadata, return ID. https://github.com/henomis/lingoose/pull/33
- [x] include more unit test https://github.com/henomis/lingoose/pull/34
- [x] check all `New` constructors and if they contain initialization of default values, consider to unexport the struct. (easy if all the struct properties are unexported)  https://github.com/henomis/lingoose/pull/35
- [x] refactor vector upsert & index creation, Create a batch upsert (100?) and check if index exists already https://github.com/henomis/lingoose/pull/36
  - batchSize = 25 default, index shouldn't be created by lingoose.
  - Document content can be inserted (as done in v0.0.3) into vectors as metadata ref: [here](https://docs.pinecone.io/docs/semantic-text-search)
- [x] provide package errors https://github.com/henomis/lingoose/pull/37
- [x] lmm metadata callback https://github.com/henomis/lingoose/pull/38
- [x] add github star button
- [x] refactor documentation following the changes of [this PR](https://github.com/henomis/lingoose/pull/35) and all related to this issue
- [x] use `String()` in prompt https://github.com/henomis/lingoose/pull/39
- [x] Add types.Meta for metadata https://github.com/henomis/lingoose/pull/40
- [x] add pdf loader https://github.com/henomis/lingoose/pull/41
- [x] refactor float64 embeddings https://github.com/henomis/lingoose/pull/42
- [x] Support whisper audio output format https://github.com/henomis/lingoose/pull/43
- [x] change embedder interface https://github.com/henomis/lingoose/pull/44
- [x] use [this](https://github.com/openai/openai-cookbook/blob/main/examples/Embedding_long_inputs.ipynb) to chunk and normalize openai embeddings https://github.com/henomis/lingoose/pull/45
    - [x] integrate [tiktoken](https://github.com/pkoukk/tiktoken-go)
