### ISSUE TITLE
release v0.0.5

### ISSUE THREAD

**Issue by henomis** [henomis/lingoose#47]
**Tasks**
- [x] add stop sequence to openai lmm constructor https://github.com/henomis/lingoose/pull/48
- [x] Constructors shouldn't return error otherwise they will not composable `a := pkg.New().WithValue().WithSome()`. https://github.com/henomis/lingoose/pull/49
- [x] `t := NewTube(llm,decoder).WithMemory(name,memory)` in general extend with methods to get optional parameters. https://github.com/henomis/lingoose/pull/50
- [x] pinecone add option to create index. consider constructor composability. https://github.com/henomis/lingoose/pull/51
- [x] add concurrent embedding using goroutines https://github.com/henomis/lingoose/pull/53
- [x] A generic loader should has optional text splitter. compose a loader with `WithSplitter(textsplitter)`. textsplitter must be an interface inside loaders. The result should be something like: `loader.NewPDFToTextLoader("/usr/bin/pdftotext", "./kb").WithSplitter(textsplitter.NewRecursiveCharacterTextSplitter(2000, 200)).Load()` https://github.com/henomis/lingoose/pull/54
- [x] are pipe templates useful? https://twitter.com/matchaman11/status/1655622928535523328?s=46&t=StJvFDFYoKhmJGuu1e_cbA https://github.com/henomis/lingoose/pull/52
- [x] refactor prompt templates https://github.com/henomis/lingoose/pull/55
- [x] refactor splitter https://github.com/henomis/lingoose/pull/57
