### ISSUE TITLE
v0.0.7

### ISSUE THREAD

**Issue by henomis** [henomis/lingoose#72]
**Tasks**
- [x] support openai completion and chat streams https://github.com/henomis/lingoose/pull/73
- [x] support hugging face conversational https://github.com/henomis/lingoose/pull/74
- [x] support hugging face text generation [model](https://huggingface.co/nomic-ai/gpt4all-j?text=My+name+is+Mariama%2C+my+favorite+TV+show+is+Friends%2C+and+I+love+making+new+friends.) [ref](https://github.com/TannerKvarfordt/hfapigo/blob/main/text_generation.go) https://github.com/henomis/lingoose/pull/75
- [x] add tesseract loader https://github.com/henomis/lingoose/pull/76
- [x] add hugging face image to text loader https://github.com/henomis/lingoose/pull/77
- [x] add hugging face speech recognition loader https://github.com/henomis/lingoose/pull/78
- [x] add hugging face sentence transformer embedder https://github.com/henomis/lingoose/pull/79
- [x] summarize https://github.com/henomis/lingoose/pull/80
