### ISSUE TITLE
v0.0.8

### ISSUE THREAD

**Issue by henomis** [henomis/lingoose#81]
**tasks:**
- [x] support Qdrant https://github.com/henomis/lingoose/pull/89
- [x] implement dalle transformer https://github.com/henomis/lingoose/pull/84
- [x] support custom openai client (discussion [here](https://github.com/henomis/lingoose/discussions/85)) https://github.com/henomis/lingoose/pull/86
- [x] support new openai models https://github.com/henomis/lingoose/pull/88
- [x] support for openai functions see [here](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_call_functions_with_chat_models.ipynb) https://github.com/henomis/lingoose/pull/90

Fun fact: started integrating qdrant official client that uses GRPC. To avoid huge imports a custom [qdrant-go](https://github.com/henomis/qdrant-go) package has beed develope,  based on my (and already imported in lingoose) [restclientgo](https://github.com/henomis/restclientgo)
