### ISSUE TITLE
v0.0.9

### ISSUE THREAD

**Issue by henomis** [henomis/lingoose#91]
## Tasks
- [x] Add LLM history https://github.com/henomis/lingoose/pull/92
- [x] Fix openai functions 🐞  https://github.com/henomis/lingoose/pull/93 https://github.com/henomis/lingoose/pull/95
- [x] the LLM should response with the JSON output of the result of function calling. don't interate! https://github.com/henomis/lingoose/pull/94
- [x] https://github.com/henomis/lingoose/pull/96
- [x] search similarity filter by metadata https://github.com/henomis/lingoose/pull/99
- [x] https://huggingface.co/dandelin/vilt-b32-finetuned-vqa https://github.com/henomis/lingoose/pull/97
- [x] exporting structs https://github.com/henomis/lingoose/pull/98
- [x] add youtube-dl loader https://github.com/henomis/lingoose/pull/100
